### ISSUE TITLE
Program crashes when searching for certain tags

### ISSUE THREAD

**Issue by installgento0** [DrabWeb/Booru-chan#1]
Xcode points an error on the following line:
post?.thumbnailUrl = self.baseUrl + xml!.element!.allAttributes["preview_url"]!.text;
Thread 1: EXC_BAD_INSTRUCTION (code=EXC_i386_INVOP, subcode=0x0)
log:
https://pastebin.com/SAJXXWdK

**Comment by DrabWeb** [comment]
Should be addressed in [v2.2.1](https://github.com/DrabWeb/Booru-chan/releases/tag/2.2.1).

**Comment by installgento0** [comment]
Thanks, it works. Btw I'm not the rude poster (62518785).
